### ISSUE TITLE
Error report when using GUI on linux

### ISSUE THREAD

**Issue by mjohannesen** [dnvgl/qats#108]
**Describe the bug**
When running the GUI on linux it works fine initially, but when exiting the GUI you get an error where it is trying to locate the qats.settings from "var/lib/qats.settings". I expect this is to update any settings changed. Possibly it is just missing a / in front, but when running it on a large computer where many people have access it might not be the best to have a global path to update

**To Reproduce**
1. Install a fresh conda environment with python 3.9 on a linux xomputer (
2. Install qats + PyQT5
3. Open GUI with qats app
4. Close GUI to get error

**Expected behavior**
No error shown

**Screenshots**
Error screenshot
![image](https://user-images.githubusercontent.com/54018005/236140050-da6b6d32-61ab-445f-b7f0-7d4ed4bea5e1.png)

Error text:
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/applications/conda/envs/qats_env/lib/python3.9/site-packages/qats/app/exceptions.py", line 37, in handle_exception
    log_file = os.path.join(os.getenv("APPDATA"), "QATS.launch.pyw.log")
  File "/home/applications/conda/envs/qats_env/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Original exception was:
Traceback (most recent call last):
  File "/home/applications/conda/envs/qats_env/lib/python3.9/site-packages/qats/app/gui.py", line 528, in closeEvent
    self.save_settings()
  File "/home/applications/conda/envs/qats_env/lib/python3.9/site-packages/qats/app/gui.py", line 1179, in save_settings
    with open(self.settings_file, "w") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'var/lib/qats.settings'
``` 

**Desktop (please complete the following information):**
 - OS: Rocky Linux
 - Version: 8.6 (Green Obsidian)

**Comment by eneelo** [comment]
@mjohannesen Good bug report - thanks!
