### ISSUE TITLE
NoneType error when displaying data from csv-files not handled properly

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#17]
Displaying a time series read from csv with _None_ creates the following error:

`ERROR - unsupported operand type(s) for *=: 'NoneType' and 'float' - Traceback (most recent call last):
  File "c:\users\ebg\venv\testing\lib\site-packages\qats\app\threading.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\ebg\venv\testing\lib\site-packages\qats\app\funcs.py", line 93, in calculate_trace
    xmin, tmin = ts.minima(twin=twin, filterargs=fargs, rettime=True)
  File "c:\users\ebg\venv\testing\lib\site-packages\qats\ts.py", line 876, in minima
    m *= -1.
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'`

In this particular case _Time History_ and _Maxima/Minima_ are not updated. The two other plots are.

**Comment by tovop** [comment]
I have not been able to reproduce the error without that specific file. Anyway the error traceback pinpoints the unhandled TypeError.
