### ISSUE TITLE
.tda import error

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#56]
In an attempt to import a .tda file directly from Sima (SIMO DYNMOD run) I get the following error:

> ERROR - [Errno 2] No such file or directory: 'C:\\Users\\ebg\\Desktop\\results.txt' - Traceback (most recent call last):
  File "c:\users\ebg\code\venv\qats\lib\site-packages\qats\app\threading.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\ebg\code\venv\qats\lib\site-packages\qats\app\funcs.py", line 282, in import_from_file
    db.load(files, read=False)
  File "c:\users\ebg\code\venv\qats\lib\site-packages\qats\tsdb.py", line 1325, in load
    names = read_tda_names(thefile.replace(fext, '.txt'))
  File "c:\users\ebg\code\venv\qats\lib\site-packages\qats\readers\direct_access.py", line 55, in read_tda_names
    names = _read_names(path)
  File "c:\users\ebg\code\venv\qats\lib\site-packages\qats\readers\direct_access.py", line 105, in _read_names
    with open(os.path.join(path, path), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ebg\\Desktop\\results.txt'

It appears as if qats misses on the file extension and tries to import results.txt instead of results.tda. Same error when importing through the File menu or by drag and drop.

**Comment by EBGlom** [comment]
Understood why it wanted results.txt. Error message could be improved.

**Comment by tovop** [comment]
Yes I agree. The files with time series and time series names must have the same basename. I guess they were not in your case
